# Rakefile for test-site
require 'yard'
require 'yard/rake/yardoc_task'
  
namespace :doc do
  root = File.dirname(__FILE__)
  dest = File.join(root, '..', 'doc', 'rdoc', 'test-site')

  desc 'Generate documentation'
  YARD::Rake::YardocTask.new(:yard) do |yt|
    yt.files   = Dir.glob(File.join(root, '**', '*.rb'))
    yt.options = ['--output-dir', dest, '--readme', File.join(root, 'README.md')]
  end
end

desc 'Run tests'
task :test do
  # None
end
